### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by wesly1988** [ChenYuHo/handwriting.js#2] opened 2019-12-20 06:22 UTC
Hi Chen, 

I am getting a strange error. 
While using the script on mobile I get the following error in console.

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as

This is on line 38 and 38 of the handwriting.canvas.js

Love the project by the way! 
Great learning resources.

**Comment by ChenYuHo** [comment] 2019-12-20 20:21
Hi @wesly1988 
Thanks for bringing this up, I actually didn't know this.
After some surveys, I concluded this was not a bug.


Quoting from [https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md):

> Passive event listeners are a new feature in the DOM spec that enables developers to opt-in to better scroll performance by eliminating the need for scrolling to block on touch and wheel event listeners.

The warning you saw is suggesting to mark event handler as **passive** to make the page more responsive.

> Developers can annotate touch and wheel listeners with {passive: true} to indicate that they will never invoke preventDefault

However, in our case, we do invoke [preventdefault](https://github.com/ChenYuHo/handwriting.js/blob/1eddc95ab8b0e4397e29fbaf67296709e89570f8/handwriting.canvas.js#L111) because we want to capture the trace and draw it on the canvas instead of invoking the default behavior (scroll).

I'm closing this issue since it's not an error, but feel free to reopen if you see other issues.

**Closed by ChenYuHo** 2019-12-20 20:21 UTC
